language: node_js
node_js:
- node
jobs:
  include:
  - script: yarn test
  - script: yarn lint
  - stage: deploy
    script:
    - umask 0077
    - openssl aes-256-cbc -K $encrypted_0cd9b55b5901_key -iv $encrypted_0cd9b55b5901_iv
      -in deploy_key.enc -out deploy_key -d
    - yarn build
    - mkdir -p ~/.ssh
    - cat fingerprints >> ~/.ssh/known_hosts
    - rsync -e "ssh -i $TRAVIS_BUILD_DIR/deploy_key" -r --inplace --delete-after $TRAVIS_BUILD_DIR/build/
      github@pfaffle.net:~/www/initiative/
stages:
- name: test
  if: branch = master OR type = pull_request
- name: deploy
  if: branch = master AND type = push
