language: node_js
node_js:
  - "node"
jobs:
  include:
    - script: yarn test
    - script: yarn lint
    - stage: build
      script: yarn build
    - stage: deploy
      script: echo todo
stages:
  - name: test
    if: branch = master OR type = pull_request
  - name: build
    if: branch = master AND type = push
  - name: deploy
    if: branch = master AND type = push
